#ifndef MOTION_CAPTURE_MOTION_CAPTURE_CHANNELS_H
#define MOTION_CAPTURE_MOTION_CAPTURE_CHANNELS_H

#define OPTITRACK_CHANNEL "OPTITRACK_CHANNEL"
#define TRUE_POSE_CHANNEL "TRUE_POSE"

#endif // MOTION_CAPTURE_MOTION_CAPTURE_CHANNELS_H
